CREATE DATABASE hoteles_caba;
USE hoteles;

CREATE TABLE hoteles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255),
  sector VARCHAR(100),
  precio DECIMAL(10,2),
  estrellas INT,
  descripcion TEXT,
  imagen varchar(400)
);

-- Insertar 50 hoteles en Palermo con direcciones en el campo 'sector'
INSERT INTO hoteles (nombre, sector, precio, estrellas, descripcion, imagen) 
VALUES
('Hotel Palermo 1', 'Av. Santa Fe 3450, Palermo', 150.00, 4, 'Hotel moderno en el corazón de Palermo, Buenos Aires. Ubicación ideal cerca de parques y bares.', 'https://www.letsbookhotel.com/img/max300/182/182847.jpg'),
('Hotel Palermo 2', 'Calle Humboldt 2600, Palermo', 200.00, 5, 'Elegante hotel boutique con piscina y gimnasio. Dirección en pleno Palermo Soho.', 'https://example.com/hotel2.jpg'),
('Hotel Palermo 3', 'Calle Gorriti 4500, Palermo', 180.00, 3, 'Hotel acogedor y tranquilo, ideal para familias. Dirección en una calle tranquila de Palermo.', 'https://example.com/hotel3.jpg'),
('Hotel Palermo 4', 'Calle Malabia 1200, Palermo', 220.00, 4, 'Hotel de lujo cerca de la Plaza Serrano, Palermo. Disfruta de la vida nocturna de la zona.', 'https://example.com/hotel4.jpg'),
('Hotel Palermo 5', 'Calle Thames 1850, Palermo', 160.00, 4, 'Hotel boutique en la zona más vibrante de Palermo Soho. Ubicación estratégica cerca de bares y restaurantes.', 'https://example.com/hotel5.jpg'),
('Hotel Palermo 6', 'Calle Fitz Roy 1500, Palermo', 140.00, 3, 'Hotel económico con una excelente ubicación en Palermo Soho. Ideal para turistas y mochileros.', 'https://example.com/hotel6.jpg'),
('Hotel Palermo 7', 'Av. Juan B. Justo 3000, Palermo', 230.00, 5, 'Hotel de 5 estrellas con spa y restaurante gourmet. Ubicación perfecta cerca de parques.', 'https://example.com/hotel7.jpg'),
('Hotel Palermo 8', 'Calle Fitz Roy 1600, Palermo', 170.00, 3, 'Ideal para turistas y viajeros de negocios. Excelente conexión con transporte público.', 'https://example.com/hotel8.jpg'),
('Hotel Palermo 9', 'Av. del Libertador 4000, Palermo', 250.00, 5, 'Hotel exclusivo con vistas al lago de Palermo. Disfruta de la serenidad de la zona.', 'https://example.com/hotel9.jpg'),
('Hotel Palermo 10', 'Calle Scalabrini Ortiz 2900, Palermo', 190.00, 4, 'Confortable y moderno, a pasos de las mejores tiendas y restaurantes de la zona.', 'https://example.com/hotel10.jpg'),
('Hotel Palermo 11', 'Calle Cnel. Niceto Vega 4600, Palermo', 175.00, 4, 'Hotel en pleno centro de Palermo Hollywood, ideal para turistas interesados en arte y cultura.', 'https://example.com/hotel11.jpg'),
('Hotel Palermo 12', 'Calle Paraguay 5000, Palermo', 210.00, 5, 'De lujo con un diseño moderno y minimalista. Excelente servicio y ubicación.', 'https://example.com/hotel12.jpg'),
('Hotel Palermo 13', 'Calle Cabrera 3400, Palermo', 200.00, 4, 'Excelente opción para disfrutar de la vida nocturna y gastronómica de Palermo.', 'https://example.com/hotel13.jpg'),
('Hotel Palermo 14', 'Calle Honduras 4000, Palermo', 160.00, 3, 'Alojamientos económicos con estilo en Palermo Soho. Perfecto para estancias largas.', 'https://example.com/hotel14.jpg'),
('Hotel Palermo 15', 'Calle Soler 2200, Palermo', 185.00, 4, 'Confortable hotel en una zona tranquila de Palermo, ideal para descansar.', 'https://example.com/hotel15.jpg'),
('Hotel Palermo 16', 'Calle Armenia 1800, Palermo', 195.00, 4, 'Hotel con jardín y área de descanso en una zona tranquila de Palermo.', 'https://example.com/hotel16.jpg'),
('Hotel Palermo 17', 'Av. Córdoba 5500, Palermo', 240.00, 5, 'Hotel de lujo con todas las comodidades modernas y vistas panorámicas.', 'https://example.com/hotel17.jpg'),
('Hotel Palermo 18', 'Av. Scalabrini Ortiz 2300, Palermo', 170.00, 3, 'Hotel boutique con una decoración moderna y espacios cómodos.', 'https://example.com/hotel18.jpg'),
('Hotel Palermo 19', 'Av. del Libertador 3500, Palermo', 210.00, 5, 'De lujo, con acceso directo a los parques de Palermo. El hotel perfecto para relajarse.', 'https://example.com/hotel19.jpg'),
('Hotel Palermo 20', 'Calle Thames 1500, Palermo', 175.00, 4, 'Ubicado cerca de los restaurantes más exclusivos de Palermo. Ambiente moderno y relajado.', 'https://example.com/hotel20.jpg'),
('Hotel Palermo 21', 'Av. Juan B. Justo 3100, Palermo', 230.00, 5, 'Hotel de 5 estrellas con restaurante, piscina y gimnasio. Ideal para turistas de lujo.', 'https://example.com/hotel21.jpg'),
('Hotel Palermo 22', 'Av. Santa Fe 3800, Palermo', 180.00, 4, 'Hotel cómodo y moderno en pleno centro de Palermo, ideal para viajeros de negocios.', 'https://example.com/hotel22.jpg'),
('Hotel Palermo 23', 'Calle Gurruchaga 2000, Palermo', 160.00, 3, 'Ideal para viajes cortos en Palermo Soho. Con una ubicación inmejorable cerca de todo.', 'https://example.com/hotel23.jpg'),
('Hotel Palermo 24', 'Av. Córdoba 5400, Palermo', 190.00, 4, 'Comodidad y estilo en pleno Palermo. Perfecto para una estadía tranquila.', 'https://example.com/hotel24.jpg'),
('Hotel Palermo 25', 'Av. Juan B. Justo 3200, Palermo', 230.00, 5, 'Hotel de lujo con acceso directo a zonas verdes y atracciones cercanas.', 'https://example.com/hotel25.jpg'),
('Hotel Palermo 26', 'Calle Fitz Roy 1700, Palermo', 180.00, 4, 'Hotel familiar con un ambiente cálido y acogedor. Con un diseño único.', 'https://example.com/hotel26.jpg'),
('Hotel Palermo 27', 'Cnel. Niceto Vega 4400, Palermo', 210.00, 5, 'Confortable y lujoso, ideal para una escapada romántica. Hotel exclusivo en la zona de moda.', 'https://example.com/hotel27.jpg'),
('Hotel Palermo 28', 'Av. Scalabrini Ortiz 2900, Palermo', 220.00, 5, 'Confort y lujo con excelente ubicación cerca de los parques de Palermo.', 'https://example.com/hotel28.jpg'),
('Hotel Palermo 29', 'Calle Humboldt 2500, Palermo', 170.00, 3, 'Alojamientos acogedores y accesibles en una de las mejores zonas de Palermo.', 'https://example.com/hotel29.jpg'),
('Hotel Palermo 30', 'Calle Nicaragua 3000, Palermo', 160.00, 3, 'Hotel moderno con excelente relación calidad-precio. Perfecto para turistas que buscan una opción económica.', 'https://example.com/hotel30.jpg'),
('Hotel Palermo 31', 'Calle Soler 1900, Palermo', 200.00, 4, 'Excelente opción para viajeros de negocios en Palermo. Ofrece todos los servicios necesarios.', 'https://example.com/hotel31.jpg'),
('Hotel Palermo 32', 'Av. Santa Fe 3500, Palermo', 180.00, 3, 'Económico y confortable. Ideal para estancias cortas en la zona de Palermo Soho.', 'https://example.com/hotel32.jpg'),
('Hotel Palermo 33', 'Av. del Libertador 4200, Palermo', 230.00, 5, 'Hotel con vistas panorámicas y excelente servicio. A pasos del Parque 3 de Febrero.', 'https://example.com/hotel33.jpg'),
('Hotel Palermo 34', 'Calle Thames 1800, Palermo', 210.00, 4, 'Ideal para disfrutar del aire libre y el ambiente relajado de los parques de Palermo.', 'https://example.com/hotel34.jpg'),
('Hotel Palermo 35', 'Calle Gorriti 4500, Palermo', 190.00, 4, 'Hotel cómodo y bien ubicado en el centro de Palermo. Perfecto para una escapada urbana.', 'https://example.com/hotel35.jpg'),
('Hotel Palermo 36', 'Av. Córdoba 5000, Palermo', 250.00, 5, 'Elegante y lujoso hotel con acceso directo a zonas verdes y parques.', 'https://example.com/hotel36.jpg'),
('Hotel Palermo 37', 'Calle Fitz Roy 1600, Palermo', 180.00, 4, 'Perfecto para turistas que desean estar cerca de la vida nocturna de Palermo.', 'https://example.com/hotel37.jpg'),
('Hotel Palermo 38', 'Av. Juan B. Justo 3300, Palermo', 210.00, 5, 'Confort y lujo en el corazón de Palermo Hollywood. Ideal para una escapada elegante.', 'https://example.com/hotel38.jpg'),
('Hotel Palermo 39', 'Av. Scalabrini Ortiz 3000, Palermo', 220.00, 5, 'Hotel exclusivo con excelente atención y ubicación ideal en Palermo.', 'https://example.com/hotel39.jpg'),
('Hotel Palermo 40', 'Calle Niceto Vega 4400, Palermo', 200.00, 4, 'Ubicado cerca de todos los puntos de interés de Palermo. Ideal para quienes buscan cultura y diversión.', 'https://example.com/hotel40.jpg'),
('Hotel Palermo 41', 'Calle Soler 2700, Palermo', 160.00, 3, 'Económico y acogedor hotel, ideal para quienes desean recorrer Palermo a pie.', 'https://example.com/hotel41.jpg'),
('Hotel Palermo 42', 'Calle Honduras 3500, Palermo', 180.00, 3, 'Comodidad y accesibilidad en un área privilegiada de Palermo Soho.', 'https://example.com/hotel42.jpg'),
('Hotel Palermo 43', 'Av. Santa Fe 3600, Palermo', 190.00, 4, 'Moderno hotel con habitaciones amplias y modernas. Ubicación estratégica.', 'https://example.com/hotel43.jpg'),
('Hotel Palermo 44', 'Calle Malabia 1500, Palermo', 210.00, 5, 'Hotel de lujo con gimnasio, spa y restaurante gourmet en el corazón de Palermo.', 'https://example.com/hotel44.jpg'),
('Hotel Palermo 45', 'Av. Córdoba 5200, Palermo', 240.00, 5, 'Exclusivo hotel con vistas al jardín japonés y a los lagos de Palermo.', 'https://example.com/hotel45.jpg'),
('Hotel Palermo 46', 'Calle Paraguay 4900, Palermo', 220.00, 5, 'Lujoso hotel con excelentes vistas, restaurante y gimnasio. A solo unos pasos de los parques.', 'https://example.com/hotel46.jpg'),
('Hotel Palermo 47', 'Calle Fitz Roy 1400, Palermo', 200.00, 4, 'Confortable y moderno hotel boutique en el corazón de Palermo Soho. Perfecto para escapadas urbanas.', 'https://example.com/hotel47.jpg'),
('Hotel Palermo 48', 'Av. del Libertador 4600, Palermo', 230.00, 5, 'Hotel exclusivo con acceso al jardín botánico y un restaurante de alta gama.', 'https://example.com/hotel48.jpg'),
('Hotel Palermo 49', 'Calle Thames 1800, Palermo', 200.00, 4, 'Hotel con ambiente cálido y moderno, ideal para viajeros que desean explorar Palermo.', 'https://example.com/hotel49.jpg'),
('Hotel Palermo 50', 'Av. Scalabrini Ortiz 3100, Palermo', 250.00, 5, 'Hotel de lujo con spa y piscina en una ubicación central en Palermo, cerca de todo.', 'https://example.com/hotel50.jpg');
